<?php echo $this->doctype();?>
<html>
    <head>

       <?php 
       echo $this->headMeta(); 
       echo $this->headLink()->appendStylesheet("/css/style.css")."\r\n";
       echo $this->headScript()->appendFile('/js/underscore.js','text/javascript',array())."\r\n";
       echo $this->headScript()->appendFile('/js/jquery.js','text/javascript',array())."\r\n";
       ?>

        <script type="text/template" id="group_list">
        <% _.each(obj,function(row){%>
            <a href="/messages/index/grupa/<%print(row.namegroup)%>"><div class="option"><%print(row.namegroup)%></div></a>
            <% });%>
        </script>
        <script type="application/javascript">
            $(document).ready(function()
            {
                var tmpUsers = _.template($("#group_list").html());
                $.getJSON("<?php echo $this->url(array('controller' => 'groups', 'action' => 'list')); ?>",
                    function( data ) {
                        var html = tmpUsers(data);
                        $("aside a").before(html);
                    });
            });
        </script>
    </head>
    <body>
<div id="container">
    <header>
        <h1>Główny tytuł strony</h1>
    </header>

    <nav>     
            <div class="option">Początek</div>
            <div class="option">Zdjęcia</div>
            <div class="option">Wideo</div>
            <div class="option">Kontakt</div>
        </nav>
    <div class="reset_float"></div>
    <div id="center">
    <aside>
        <?php
        $auth = Zend_Auth::getInstance();
        $logged = $auth->hasIdentity();
        if(!$logged)
        {
            echo "<!--";
        }
        ?>
            <div class="option">Lista grup</div>
        <?php
        if(!$logged)
        {
            echo "-->";
            echo '
           <a href="/users/login"> <div class="option">Zaloguj</div></a>
            <a href="/users/add"> <div class="option">Zarejestruj</div></a>
            ';
        }
        else
        {
            echo '
           <a href="/users/logout"> <div class="option">Wyloguj</div></a>
            ';
        }
        ?>

    </aside>
    <section>
        <article>

                <?php
                echo $this->layout()->content;
                echo $this->view;
                ?>
        <span class="comment">Komentarzy (0)</span>
        </article>
    </section>
    <div class="reset_float"></div>
    </div>
    <div class="line">&nbsp;</div>
    <footer> Copyright @ 2015</footer>
</div>
</body>
</html>
