<?php echo $this->doctype();?>
<html>
    <head>

       <?php 
       echo $this->headMeta(); 
       echo $this->headLink()->appendStylesheet("/css/style.css")."\r\n";
       echo $this->headScript()->appendFile('/js/underscore.js','text/javascript',array())."\r\n";
       echo $this->headScript()->appendFile('/js/jquery.js','text/javascript',array())."\r\n";
       ?>
    </head>
    <body>
<div id="container">
    <header>
        <h1>Główny tytuł strony</h1>
    </header>

    <nav>     
            <div class="option">Początek</div>
            <div class="option">Zdjęcia</div>
            <div class="option">Wideo</div>
            <div class="option">Kontakt</div>
        </nav>
    <div class="reset_float"></div>
    <div id="center">
    <aside>
            <div class="option">Opcja 1</div>
            <div class="option">Opcja 1</div>
            <div class="option">Opcja 1</div>
    </aside>
    <section>
        <article>

                <?php
                echo $this->layout()->content;
                echo $this->view;
                ?>
        <span class="comment">Komentarzy (0)</span>
        </article>
    </section>
    <div class="reset_float"></div>
    </div>
    <div class="line">&nbsp;</div>
    <footer> Copyright @ 2015</footer>
</div>
</body>
</html>
